export const peopleActionTypes = {
    FETCH_PEOPLE_REDUX_SAGA_START: "FETCH_PEOPLE_REDUX_SAGA_START",
    FETCH_PEOPLE_REDUX_THUNK_START: "FETCH_PEOPLE_REDUX_THUNK_START",
    FETCH_PEOPLE_SUCCESS: "FETCH_PEOPLE_SUCCESS",
    FETCH_PEOPLE_FAILURE: "FETCH_PEOPLE_FAILURE",
}