export const bkmActionTypes = {
    FETCH_BKM_LIST_START: "FETCH_BKM_LIST_START",
    FETCH_BKM_LIST_SUCCESS: "FETCH_BKM_LIST_SUCCESS",
    FETCH_BKM_LIST_FAILURE: "FETCH_BKM_LIST_FAILURE",
    FETCH_BKM_ITEM_START: "FETCH_BKM_ITEM_START",
    FETCH_BKM_ITEM_SUCCESS: "FETCH_BKM_ITEM_SUCCESS",
    FETCH_BKM_ITEM_FAILURE: "FETCH_BKM_ITEM_FAILURE",

    SEARCH_INPUT_NAME_BKM: "SEARCH_INPUT_NAME_BKM",
}